/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.AptDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Appartment;

/**
 *
 * @author JOHN SHADARY
 */
public class HomeBoard extends javax.swing.JFrame {
    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form HomeBoard
     */
    public HomeBoard() {
        initComponents();
        addColumns();
        RetrieveApts();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void EmpyFields(){
         aptType.setSelectedIndex(0);
         priceTxt.setText("");
         districtTxt.setText("");
         sectorTxt.setText("");
         cityTxt.setText("");
         aptStatus.setSelectedIndex(0);
     }
    
    public void RetrieveApts() {
        AptDao dao = new AptDao();
        dao.Display(tableModel, "Admin");
    }
    
    private boolean Validation (){
        if(aptType.getSelectedIndex() ==0
           || priceTxt.getText().trim().isEmpty()
           || districtTxt.getText().trim().isEmpty() 
           || sectorTxt.getText().trim().isEmpty() 
           || cityTxt.getText().trim().isEmpty()
           || aptStatus.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Provide data", "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void InsertAppartment() {
        Appartment thisApt = new Appartment();
        thisApt.setAppartmentType((String)  aptType.getSelectedItem());
        thisApt.setAppartmentPrice(Double.parseDouble(priceTxt.getText()));
        thisApt.setDistrict(districtTxt.getText());
        thisApt.setSector(sectorTxt.getText());
        thisApt.setCity(cityTxt.getText());
        thisApt.setAppartmentStatus((String) aptStatus.getSelectedItem());
        
        
         AptDao dao = new AptDao();
        int rows = dao.AddApt(thisApt);
        if (rows > 0){
            JOptionPane.showMessageDialog(this, "Appartment added successfully!", "Recorded",JOptionPane.INFORMATION_MESSAGE);

            tableModel = new DefaultTableModel();
            addColumns();
            RetrieveApts();
            return;
        }else{
            JOptionPane.showMessageDialog(this, "Failed to add the appartment!", "Try again", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    private void UpdateAppartment(){
         
        int feedBack = JOptionPane.showConfirmDialog(this,
                "Are you sure to edit this record!", "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(feedBack == 0) System.out.println("Not Updated");
        else return;
        
        Appartment thisApt = new Appartment();
        thisApt.setAppartmentType((String) aptType.getSelectedItem());
        thisApt.setAppartmentPrice(Double.parseDouble(priceTxt.getText()));
        
        thisApt.setDistrict(districtTxt.getText());
        thisApt.setSector(sectorTxt.getText());
        thisApt.setCity(cityTxt.getText());
        thisApt.setAppartmentStatus((String) aptStatus.getSelectedItem());

        AptDao dao = new AptDao();
        int selectedRowIndex = appartmentDetails.getSelectedRow();
        int rowAffected = dao.UpdateApt(thisApt, Integer.parseInt(tableModel.getValueAt(selectedRowIndex, 0).toString()));

        if(rowAffected > 0) {
            JOptionPane.showMessageDialog(this,
                    "Record successfully updated", "Information",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        tableModel = new DefaultTableModel();
        addColumns();
        RetrieveApts();
    }
    
    private void addColumns() {
        tableModel.addColumn("Appartment Id");
        tableModel.addColumn("Appartment Type");
        tableModel.addColumn("Price");
        tableModel.addColumn("District");
        tableModel.addColumn("Sector");
        tableModel.addColumn("City");
        tableModel.addColumn("Appartment Status");
       
        appartmentDetails.setModel(tableModel);
    }
    private void DeleteAppartment(){
        int feedBack = JOptionPane.showConfirmDialog(this, "You are about to delete the record",
                "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
        if(feedBack == 0) System.out.println("Not deleted");
        else return;

        AptDao dao = new AptDao();
        int selectedRowIndex = appartmentDetails.getSelectedRow();
        int rows = dao.DeleteApt(Integer.parseInt(tableModel.getValueAt(selectedRowIndex, 0).toString()));

        if(rows > 0) {
            JOptionPane.showMessageDialog(this,
                    "Record successfully deleted ",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        tableModel = new DefaultTableModel();
        addColumns();
        RetrieveApts();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        districtTxt = new javax.swing.JTextField();
        sectorTxt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        aptStatus = new javax.swing.JComboBox<>();
        aptType = new javax.swing.JComboBox<>();
        OutBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        appartmentDetails = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Administrator DashBoard");

        jLabel2.setText("Appartment Type");

        jLabel3.setText("Price");

        jLabel4.setText("District");

        jLabel5.setText("Sector");

        jLabel6.setText("City");

        priceTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTxtKeyTyped(evt);
            }
        });

        districtTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                districtTxtKeyTyped(evt);
            }
        });

        sectorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectorTxtActionPerformed(evt);
            }
        });
        sectorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sectorTxtKeyTyped(evt);
            }
        });

        cityTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityTxtKeyTyped(evt);
            }
        });

        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Appartment Status");

        aptStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Available", "Rented", "In Reparation" }));

        aptType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Family", "Studio",  }));

        OutBtn.setText("(|) LogOut");
        OutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Client Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(insertBtn)
                    .addComponent(jLabel7))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceTxt)
                    .addComponent(districtTxt)
                    .addComponent(sectorTxt)
                    .addComponent(cityTxt)
                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(aptStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aptType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(deleteBtn)
                        .addGap(49, 49, 49)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(OutBtn))
                        .addGap(119, 119, 119))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(aptType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(OutBtn)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(districtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sectorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aptStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        appartmentDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appartmentDetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(appartmentDetails);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sectorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectorTxtActionPerformed

    private void OutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutBtnActionPerformed
        // TODO add your handling code here:
        LoginUI lU = new LoginUI();
        lU.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_OutBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminBoard aB = new AdminBoard();
        aB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        boolean isValid = Validation();
        if(isValid)
          InsertAppartment();
        EmpyFields();
        
    }//GEN-LAST:event_insertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        boolean isValid = Validation();
        if(isValid)
            UpdateAppartment();
        EmpyFields();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void appartmentDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appartmentDetailsMouseClicked
        // TODO add your handling code here:
        int row = appartmentDetails.getSelectedRow();
         int idColumnIndex = 0; // Assuming "id" is the first column

        if (row != -1) {
            Object idObject = appartmentDetails.getValueAt(row, idColumnIndex);
            if (idObject != null) {
                
                String appartmentType = appartmentDetails.getValueAt(row, 1).toString();
                String appartmentPrice = appartmentDetails.getValueAt(row, 2).toString();
                String district = appartmentDetails.getValueAt(row, 3).toString();
                String sector = appartmentDetails.getValueAt(row, 4).toString();
                String city = appartmentDetails.getValueAt(row, 5).toString();
                String status = appartmentDetails.getValueAt(row, 6).toString();

                aptType.setSelectedItem(appartmentType);
                priceTxt.setText(appartmentPrice);
                districtTxt.setText(district);
                sectorTxt.setText(sector);
                cityTxt.setText(city);
                aptStatus.setSelectedItem(status);
        }
}
    }//GEN-LAST:event_appartmentDetailsMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        boolean isValid = Validation();
        if(isValid)
            DeleteAppartment();
        EmpyFields();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void priceTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTxtKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_priceTxtKeyTyped

    private void districtTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_districtTxtKeyTyped
        // TODO add your handling code here:
        char KeyChar = evt.getKeyChar();
        boolean digit = Character.isDigit(KeyChar);
        
        if(digit){
            evt.consume();
        }
    }//GEN-LAST:event_districtTxtKeyTyped

    private void sectorTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sectorTxtKeyTyped
        // TODO add your handling code here:
        char KeyChar = evt.getKeyChar();
        boolean digit = Character.isDigit(KeyChar);
        
        if(digit){
            evt.consume();
        }
    }//GEN-LAST:event_sectorTxtKeyTyped

    private void cityTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityTxtKeyTyped
        // TODO add your handling code here:
        
        char KeyChar = evt.getKeyChar();
        boolean digit = Character.isDigit(KeyChar);
        
        if(digit){
            evt.consume();
        }
    }//GEN-LAST:event_cityTxtKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EmpyFields();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OutBtn;
    private javax.swing.JTable appartmentDetails;
    private javax.swing.JComboBox<String> aptStatus;
    private javax.swing.JComboBox<String> aptType;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField districtTxt;
    private javax.swing.JButton insertBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField sectorTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
